
CHANCE_AGUA = 0.2

ENERGIA_INICIAL_COELHO = 30
CONSUMO_ENERGIA_COELHO = 5
PERCEPCAO_COELHO = 3

ENERGIA_INICIAL_COBRA = 50
CONSUMO_ENERGIA_COBRA = 8
PERCEPCAO_COBRA = 6

ENERGIA_INICIAL_GAVIAO = 60
CONSUMO_ENERGIA_GAVIAO = 12
PERCEPCAO_GAVIAO = 15



